service: blog-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1 
  stage: dev 
  environment:
    PORT: 3000
    MONGODB_URI: ${env:MONGODB_URI}
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  app:
    handler: app.handler
    events:
      - httpApi: 
          path: /
          method: ANY
      - httpApi:
          path: '{proxy+}' # Capture all routes
          method: ANY


package:
  exclude:
    - node_modules/**
    - test/**
    - .vscode/**
    - .env


